# Groq API Configuration
# Get your API key from: https://console.groq.com/keys

[groq]
api_key = "Your_Groq_API_key_over_here"
base_url = "https://api.groq.com/openai/v1"
model = "llama3-8b-8192"  # Available models: "llama3-8b-8192", "mixtral-8x7b-32768", "gemma-7b-it"

[settings]
max_tokens = 1000
temperature = 0.7
timeout = 30

# Usage example in Python:
# import toml
# config = toml.load("secrets/groq_api.toml")
# api_key = config["groq"]["api_key"]